version: '3'
services:
  service:
    container_name: 'halter-rewards'
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb/halter-rewards
      - NODE_ENV=development
      - PORT=5000
    networks:
      - halter-rewards-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image: 'mongo'
    container_name: 'halter-rewards-mongodb'
    networks:
      - halter-rewards-network
    volumes:
      - ./.tmp/mongo-volume:/data/db
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019

networks:
  halter-rewards-network:
    driver: bridge
    name: backend-network
